### ISSUE TITLE
Site not rebuilding with docker when changing code

### ISSUE THREAD

**Issue by gflohr** [gflohr/qgoda#88]
@veronikaneumann reported this originally as https://github.com/gflohr/qgoda-site/issues/6:

When I run `docker run --rm -it -v $(pwd):/data gflohr/qgoda watch` for the first time, I get this:

```bash
Unable to find image 'gflohr/qgoda:latest' locally
latest: Pulling from gflohr/qgoda
32802c0cfa4d: Pull complete 
da1315cffa03: Pull complete 
fa83472a3562: Pull complete 
f85999a86bef: Pull complete 
2f34af37591d: Pull complete 
5d61b24be09e: Pull complete 
11de23fee31f: Pull complete 
5bc666f76fe6: Pull complete 
c4bff6b4f289: Pull complete 
0254bf180e19: Pull complete 
1b844f0d8db6: Pull complete 
adab1f06950d: Pull complete 
1fc670733f6b: Pull complete 
27f72511e8cf: Pull complete 
Digest: sha256:6809ae59a76475f2168262392910ad5ce7bedc025ddc7724a865bdfaa0f59edb
Status: Downloaded newer image for gflohr/qgoda:latest
[Mon Mar 16 15:43:36.76455 2020][warning][config] config file '_config.yaml' not found, proceeding with defaults.
[Mon Mar 16 15:43:37.20666 2020][info][plugin-loader] initializing plug-ins.
[Mon Mar 16 15:43:37.20687 2020][info] start building site
[Mon Mar 16 15:43:37.20770 2020][info] finished building site with 0 artefacts
[Mon Mar 16 15:43:37.20784 2020][info] 0 artefacts were changed and have been re-written
```

When I change my code afterwards, I expect to get something like this:
```bash
[...] start rebuilding site because of file system change
```

But nothing happens. Is it a problem that I don't have a _config.yaml? Why does it say that I have 0 artefacts? Am I doing something wrong or is this an issue of the image?

(I found an older image dsonntag/qgoda on my server and got it working with this one as expected.)

**Comment by gflohr** [comment]
I had rewritten and replaced AnyEvent-Filesys-Notify because I wanted to get rid of the dependency to Moose. This may have introduced the bug.  I will undo that change and try to build a new docker image. Unfortunately, that won't happen before next week. Okay?

**Comment by veronikaneumann** [comment]
Yes, that's totally fine. Thanks in advance!
