### ISSUE TITLE
Qgoda 0.9.7 namespace overlap with URI::git

### ISSUE THREAD

**Issue by ehuelsmann** [gflohr/qgoda#90]
Hi,

https://metacpan.org/release/URI-git seems to be the owner of the URI::git namespace - which results in "UNAUTHORIZED" warning at the bottom of https://metacpan.org/release/Qgoda.

**Comment by gflohr** [comment]
Yes, thanks for the reminder! That was a workaround I had forgotten.  Will look at it now.
